-- MySQL Script generated by MySQL Workbench
-- tipo_cuentaTue Aug 15 20:41:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Checkpoint1-mesa18
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Checkpoint1-mesa18
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Checkpoint1-mesa18` DEFAULT CHARACTER SET utf8 ;
USE `Checkpoint1-mesa18` ;

-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`pais` (
  `idpais` INT NOT NULL AUTO_INCREMENT,
  `nombre_pais` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`ciudad` (
  `idciudad` INT NOT NULL AUTO_INCREMENT,
  `nombre_ciudad` VARCHAR(100) NOT NULL,
  `pais_idpais` INT NOT NULL,
  PRIMARY KEY (`idciudad`),
  INDEX `fk_ciudad_pais_idx` (`pais_idpais` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_pais`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `Checkpoint1-mesa18`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`sucursal` (
  `idsucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  `codigo_postal` VARCHAR(10) NOT NULL,
  `ciudad_idciudad` INT NOT NULL,
  PRIMARY KEY (`idsucursal`),
  INDEX `fk_sucursal_ciudad1_idx` (`ciudad_idciudad` ASC) VISIBLE,
  CONSTRAINT `fk_sucursal_ciudad1`
    FOREIGN KEY (`ciudad_idciudad`)
    REFERENCES `Checkpoint1-mesa18`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `domicilio` VARCHAR(100) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `movil` VARCHAR(20) NULL,
  `ciudad_idciudad` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_ciudad1_idx` (`ciudad_idciudad` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_ciudad1`
    FOREIGN KEY (`ciudad_idciudad`)
    REFERENCES `Checkpoint1-mesa18`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`tipo_cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`tipo_cuenta` (
  `idtipo_cuenta` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idtipo_cuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `domicilio` VARCHAR(100) NULL,
  `email` VARCHAR(70) NULL,
  `movil` VARCHAR(45) NULL,
  `fecha_alta_contrato` DATE NULL,
  `sucursal_idsucursal` INT NOT NULL,
  `ciudad_idciudad` INT NOT NULL,
  PRIMARY KEY (`idempleado`),
  INDEX `fk_empleado_sucursal1_idx` (`sucursal_idsucursal` ASC) VISIBLE,
  INDEX `fk_empleado_ciudad1_idx` (`ciudad_idciudad` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_sucursal1`
    FOREIGN KEY (`sucursal_idsucursal`)
    REFERENCES `Checkpoint1-mesa18`.`sucursal` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_ciudad1`
    FOREIGN KEY (`ciudad_idciudad`)
    REFERENCES `Checkpoint1-mesa18`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`cuenta` (
  `idcuenta` INT NOT NULL AUTO_INCREMENT,
  `tipo_cuenta_idtipo_cuenta` INT NOT NULL,
  `sucursal_idsucursal` INT NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `saldo_cuenta` INT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idcuenta`),
  INDEX `fk_cuenta_tipo_cuenta1_idx` (`tipo_cuenta_idtipo_cuenta` ASC) VISIBLE,
  INDEX `fk_cuenta_sucursal1_idx` (`sucursal_idsucursal` ASC) VISIBLE,
  INDEX `fk_cuenta_empleado1_idx` (`empleado_idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_cuenta_tipo_cuenta1`
    FOREIGN KEY (`tipo_cuenta_idtipo_cuenta`)
    REFERENCES `Checkpoint1-mesa18`.`tipo_cuenta` (`idtipo_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_sucursal1`
    FOREIGN KEY (`sucursal_idsucursal`)
    REFERENCES `Checkpoint1-mesa18`.`sucursal` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `Checkpoint1-mesa18`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`cliente_has_cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`cliente_has_cuenta` (
  `idcliente_has_cuenta` INT NOT NULL AUTO_INCREMENT,
  `cliente_idcliente` INT NOT NULL,
  `cuenta_idcuenta` INT NOT NULL,
  PRIMARY KEY (`idcliente_has_cuenta`),
  INDEX `fk_cliente_has_cuenta_cuenta1_idx` (`cuenta_idcuenta` ASC) VISIBLE,
  INDEX `fk_cliente_has_cuenta_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_cuenta_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `Checkpoint1-mesa18`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_cuenta_cuenta1`
    FOREIGN KEY (`cuenta_idcuenta`)
    REFERENCES `Checkpoint1-mesa18`.`cuenta` (`idcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`historial_cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`historial_cuenta` (
  `idhistorial_cuenta` INT NOT NULL AUTO_INCREMENT,
  `historial_acceso` DATETIME NOT NULL,
  `cliente_has_cuenta_idcliente_has_cuenta` INT NOT NULL,
  PRIMARY KEY (`idhistorial_cuenta`),
  INDEX `fk_historial_cuenta_cliente_has_cuenta1_idx` (`cliente_has_cuenta_idcliente_has_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_historial_cuenta_cliente_has_cuenta1`
    FOREIGN KEY (`cliente_has_cuenta_idcliente_has_cuenta`)
    REFERENCES `Checkpoint1-mesa18`.`cliente_has_cuenta` (`idcliente_has_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`descubierto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`descubierto` (
  `iddescubierto` INT NOT NULL,
  `cant_descubierto` INT NULL,
  `tipo_cuenta_idtipo_cuenta` INT NOT NULL,
  PRIMARY KEY (`iddescubierto`),
  INDEX `fk_cuenta_corriente_tipo_cuenta1_idx` (`tipo_cuenta_idtipo_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_cuenta_corriente_tipo_cuenta1`
    FOREIGN KEY (`tipo_cuenta_idtipo_cuenta`)
    REFERENCES `Checkpoint1-mesa18`.`tipo_cuenta` (`idtipo_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`tipo_interes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`tipo_interes` (
  `idtipo_interes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `tipo_cuenta_idtipo_cuenta` INT NOT NULL,
  PRIMARY KEY (`idtipo_interes`),
  INDEX `fk_caja_ahorro_tipo_cuenta1_idx` (`tipo_cuenta_idtipo_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_caja_ahorro_tipo_cuenta1`
    FOREIGN KEY (`tipo_cuenta_idtipo_cuenta`)
    REFERENCES `Checkpoint1-mesa18`.`tipo_cuenta` (`idtipo_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`prestamo` (
  `idprestamo` INT NOT NULL AUTO_INCREMENT,
  `fecha_otorgamiento` DATE NULL,
  `importe` INT NULL,
  `cant_cuotas` INT NULL,
  `sucursal_idsucursal` INT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idprestamo`),
  INDEX `fk_prestamo_sucursal1_idx` (`sucursal_idsucursal` ASC) VISIBLE,
  INDEX `fk_prestamo_empleado1_idx` (`empleado_idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_prestamo_sucursal1`
    FOREIGN KEY (`sucursal_idsucursal`)
    REFERENCES `Checkpoint1-mesa18`.`sucursal` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamo_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `Checkpoint1-mesa18`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`pago` (
  `idpago` INT NOT NULL AUTO_INCREMENT,
  `numero_cuota` INT NULL,
  `fecha_hora` DATETIME NULL,
  `importe` INT NULL,
  `prestamo_idprestamo` INT NOT NULL,
  PRIMARY KEY (`idpago`),
  INDEX `fk_pago_prestamo1_idx` (`prestamo_idprestamo` ASC) VISIBLE,
  CONSTRAINT `fk_pago_prestamo1`
    FOREIGN KEY (`prestamo_idprestamo`)
    REFERENCES `Checkpoint1-mesa18`.`prestamo` (`idprestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkpoint1-mesa18`.`prestamo_has_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Checkpoint1-mesa18`.`prestamo_has_cliente` (
  `idprestamo_has_cliente` INT NOT NULL AUTO_INCREMENT,
  `prestamo_idprestamo` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  INDEX `fk_prestamo_has_cliente_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_prestamo_has_cliente_prestamo1_idx` (`prestamo_idprestamo` ASC) VISIBLE,
  PRIMARY KEY (`idprestamo_has_cliente`),
  CONSTRAINT `fk_prestamo_has_cliente_prestamo1`
    FOREIGN KEY (`prestamo_idprestamo`)
    REFERENCES `Checkpoint1-mesa18`.`prestamo` (`idprestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamo_has_cliente_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `Checkpoint1-mesa18`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Modificaciones DML CRUD
-- Comentarios:
-- Se creó entidad país además de ciudad.
-- Definimos codigo postal a cada sucursal
-- -----------------------------------------------------



INSERT INTO `checkpoint1-mesa18`.`tipo_cuenta`
(`idtipo_cuenta`,
`tipo`)
VALUES
(default, "C.A."),(default,"C.C."),(default,"Otras");

select * from tipo_cuenta;

INSERT INTO `checkpoint1-mesa18`.`tipo_interes`
(`idtipo_interes`,
`nombre`,
`tipo_cuenta_idtipo_cuenta`)
VALUES
(default, "Interes fijo", 1), (default, "Interes Variable",1), (default, "Otros intereses",1);

select * from tipo_interes;

UPDATE `checkpoint1-mesa18`.`tipo_cuenta`
SET
`tipo` = "Caja de Ahorros"
WHERE `idtipo_cuenta` = 1;


UPDATE `checkpoint1-mesa18`.`tipo_cuenta`
SET
`tipo` = "Cuenta Corriente"
WHERE `idtipo_cuenta` = 2;

DELETE FROM `checkpoint1-mesa18`.`tipo_cuenta`
WHERE idtipo_cuenta = 3;