-- MySQL Script generated by MySQL Workbench
-- Thu Aug 10 21:08:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bibliotecaDH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bibliotecaDH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliotecaDH` DEFAULT CHARACTER SET utf8 ;
USE `bibliotecaDH` ;

-- -----------------------------------------------------
-- Table `bibliotecaDH`.`editorial_has_libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaDH`.`editorial_has_libro` (
  `editorial_ideditorial` INT NOT NULL,
  `libro_codigoInterno` INT NOT NULL,
  `ideditorial_has_librocol` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ideditorial_has_librocol`),
  INDEX `fk_editorial_has_libro_libro1_idx` (`libro_codigoInterno` ASC) VISIBLE,
  INDEX `fk_editorial_has_libro_editorial1_idx` (`editorial_ideditorial` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaDH`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaDH`.`autor` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaDH`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaDH`.`editorial` (
  `id_editorial` INT NOT NULL AUTO_INCREMENT,
  `razon_social` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id_editorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaDH`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaDH`.`libro` (
  `codigo_interno` INT NOT NULL AUTO_INCREMENT,
  `ISBN` VARCHAR(45) NULL DEFAULT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `anio_escrito` DATE NULL DEFAULT NULL,
  `anio_edicion` DATE NULL DEFAULT NULL,
  `autor_idautor` INT NOT NULL,
  `editorial_id_editorial` INT NOT NULL,
  PRIMARY KEY (`codigo_interno`),
  INDEX `fk_libro_autor1_idx` (`autor_idautor` ASC) VISIBLE,
  INDEX `fk_libro_editorial1_idx` (`editorial_id_editorial` ASC) VISIBLE,
  CONSTRAINT `fk_libro_autor1`
    FOREIGN KEY (`autor_idautor`)
    REFERENCES `bibliotecaDH`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_editorial1`
    FOREIGN KEY (`editorial_id_editorial`)
    REFERENCES `bibliotecaDH`.`editorial` (`id_editorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaDH`.`socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaDH`.`socio` (
  `id_socio` INT NOT NULL AUTO_INCREMENT,
  `DNI` CHAR(8) NOT NULL,
  `direccion` VARCHAR(70) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_socio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaDH`.`telefonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaDH`.`telefonos` (
  `id_telefonos` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(15) NULL DEFAULT NULL,
  `editorial_ideditorial` INT NOT NULL,
  PRIMARY KEY (`id_telefonos`),
  INDEX `fk_telefonos_editorial1_idx` (`editorial_ideditorial` ASC) VISIBLE,
  CONSTRAINT `fk_telefonos_editorial1`
    FOREIGN KEY (`editorial_ideditorial`)
    REFERENCES `bibliotecaDH`.`editorial` (`id_editorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaDH`.`copia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaDH`.`copia` (
  `id_copia` INT NOT NULL AUTO_INCREMENT,
  `deterioro` TINYINT(1) NOT NULL,
  `libro_codigoInterno` INT NOT NULL,
  PRIMARY KEY (`id_copia`),
  INDEX `fk_copia_libro1_idx` (`libro_codigoInterno` ASC) VISIBLE,
  CONSTRAINT `fk_copia_libro1`
    FOREIGN KEY (`libro_codigoInterno`)
    REFERENCES `bibliotecaDH`.`libro` (`codigo_interno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaDH`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaDH`.`prestamo` (
  `id_prestamo` INT NOT NULL AUTO_INCREMENT,
  `fecha_retiro` DATE NULL DEFAULT NULL,
  `fecha_tope` DATE NULL DEFAULT NULL,
  `fecha_real_devolucion` DATE NULL DEFAULT NULL,
  `socio_idsocio` INT NOT NULL,
  PRIMARY KEY (`id_prestamo`),
  INDEX `fk_prestamo_socio1_idx` (`socio_idsocio` ASC) VISIBLE,
  CONSTRAINT `fk_prestamo_socio1`
    FOREIGN KEY (`socio_idsocio`)
    REFERENCES `bibliotecaDH`.`socio` (`id_socio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaDH`.`telefono-socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaDH`.`telefono-socio` (
  `id_telefono_socio` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(15) NULL,
  `socio_idsocio` INT NOT NULL,
  PRIMARY KEY (`id_telefono_socio`),
  INDEX `fk_telefono-socio_socio1_idx` (`socio_idsocio` ASC) VISIBLE,
  CONSTRAINT `fk_telefono-socio_socio1`
    FOREIGN KEY (`socio_idsocio`)
    REFERENCES `bibliotecaDH`.`socio` (`id_socio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaDH`.`copia_has_prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaDH`.`copia_has_prestamo` (
  `id_copia_has_prestamocol` INT NOT NULL AUTO_INCREMENT,
  `copia_id_copia` INT NOT NULL,
  `prestamo_id_prestamo` INT NOT NULL,
  PRIMARY KEY (`id_copia_has_prestamocol`),
  INDEX `fk_copia_has_prestamo_prestamo1_idx` (`prestamo_id_prestamo` ASC) VISIBLE,
  INDEX `fk_copia_has_prestamo_copia1_idx` (`copia_id_copia` ASC) VISIBLE,
  CONSTRAINT `fk_copia_has_prestamo_copia1`
    FOREIGN KEY (`copia_id_copia`)
    REFERENCES `bibliotecaDH`.`copia` (`id_copia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_copia_has_prestamo_prestamo1`
    FOREIGN KEY (`prestamo_id_prestamo`)
    REFERENCES `bibliotecaDH`.`prestamo` (`id_prestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
